#!/bin/bash

# Set history time format (if not already set)
export HISTTIMEFORMAT='%F %T '

# Reload the history to apply time format
history -r

# Print the history with timestamps
echo "Command History with Execution Timestamps:"
history | while read -r line; do
    # Separate the number and the rest
    cmd_number=$(echo "$line" | awk '{print $1}')
    cmd_content=$(echo "$line" | cut -d' ' -f2-)
    
    echo "$cmd_number: $cmd_content"
done